# Generated by Django 3.0.8 on 2020-07-06 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_auto_20200704_1630'),
        ('carts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='games',
            field=models.ManyToManyField(through='carts.CartGames', to='games.Game'),
        ),
    ]
